module.exports = {
  'EMERALD_BLADE': '../resources/custom/items/melee/emerald_blade.png',
  'EDIBLE_MACE': '../resources/custom/items/melee/edible_mace.png',
  'ASPECT_OF_THE_DRAGONS': '../resources/custom/items/melee/aspect_dragon.png',
  'ASPECT_OF_THE_END': '../resources/custom/items/melee/aspect_of_the_end.png',
  'FROZEN_SCYTHE': '../resources/custom/items/melee/frozen_scythe.png',
  'LEAPING_SWORD': '../resources/custom/items/melee/leaping_sword.png',
  'ZOMBIE_SWORD_T2': '../resources/custom/items/melee/ornatezombiesword.png',
  'ZOMBIE_SWORD_T3': '../resources/custom/items/melee/floridzombiesword.png',
  'POOCH_SWORD': '../resources/custom/items/melee/pooch_sword.png',
  'PRISMARINE_BLADE': '../resources/custom/items/melee/prismarine_blade.png',
  'REAPER_FALCHION': '../resources/custom/items/melee/reaper_falchion.png',
  'ROGUE_SWORD': '../resources/custom/items/melee/rogue_sword.png',
  'GRAPPLING_HOOK': '../resources/custom/items/tools/grapple_hook.png',
  'AUTO_RECOMBOBULATOR': '../resources/custom/items/accessories/auto_recombobulator.png',
  'PIGGY_BANK': '../resources/custom/items/accessories/piggy_bank.png',
  'TARANTULA_TALISMAN': '../resources/custom/items/accessories/tarantula_talisman.png',
  'PERFECT_TALISMAN': '../resources/custom/items/accessories/perfect_talisman.png',
  'FARMING_TALISMAN': '../resources/custom/items/accessories/farming_talisman.png',
  'OVERFLUX_CAPACITOR': '../resources/custom/items/other/power_orbs/overflux_capacitor.png',
  'RADIANT_POWER_ORB': '../resources/custom/items/other/power_orbs/radiant_power_orb.png',
  'MANA_FLUX_POWER_ORB': '../resources/custom/items/other/power_orbs/mana_flux_power_orb.png',
  'OVERFLUX_POWER_ORB': '../resources/custom/items/other/power_orbs/overflux_power_orb.png',
  'PLASMAFLUX_POWER_ORB': '../resources/custom/items/other/power_orbs/plasmaflux_power_orb.png',
}